configuration:
  dependencies:
  - "mvn://org.python:jython-standalone:2.7.1"
  arguments:
    x: "NULL"

flows:
  default:
  - form: myForm
  - log: "We got your order count: ${myForm.ordercnt}"
  - log: "URL is http://docker.for.mac.host.internal:1000/api/v1/order/create/?count=${myForm.ordercnt}"
  - task: http
    in:
      method: GET
      url: "http://docker.for.mac.host.internal:1000/api/v1/order/create/?count=${myForm.ordercnt}"
      response: string
      out: jsonResponse
  - if: ${jsonResponse.success}
    then:
     - log: "Response received as ${jsonResponse.content}"
  - set:
      x: "${jsonResponse.content}"
  - script: my_logic1.py
  - log: "itemlist is ${itemlist} with counts as ${itemcounts}"
  - script: my_logic2.py
  - log: "Final count is ${finalcount}"

forms:
  myForm:
  - ordercnt: { label: "Enter Order Count: ", type: "int?" }

triggers:
- cron:
    spec: "* * * * *" # run every minute
    timezone: "America/Toronto"
    entryPoint: default
