flows:
  default:
  - log: "Hello Concord User"

  azureQueueFlow:
  - log: "Triggered Azure flow for queue mypubq. Received message: ${event.message}"

triggers:
- azure:
    namespace: "mypubsb"
    queue: "mypubq"
    entryPoint: azureQueueFlow
    arguments:
      org: "Default"
      sharedAccessKeyName: "myasbkey"
      sharedAccessKey: "mykey"
      concordApiKey: mytoken ##"2EDHSCPL7ZKYjPjRIMkHYg"
