flows:
  default:
  - log: "Hello Concord User"

  azureQueueFlow:
  - log: "Triggered Azure flow for queue mypubq. Received message: ${event.message}"

```
  azureTopicFlow:
  - log: "Triggered Azure flow for topic pparikh-topic-1. Received message: ${event.message}"

  pcpEvent:
  - log: "Triggered Pcp flow for queue pcp-test-queue. Received message: ${event.message}"
```
triggers:
- azure:
    namespace: "rrs-test"
    queue: "mypubq"
    entryPoint: azureQueueFlow
    arguments:
      org: "Default"
      sharedAccessKeyName: "mypubstorageacc"
      sharedAccessKey: "mykey"
      concordApiKey: mytoken ##"2EDHSCPL7ZKYjPjRIMkHYg"
