configuration:
  dependencies:
  - "mvn://org.python:jython-standalone:2.7.1"
  arguments:
    x: "NULL"

flows:
  default:
  - log: "URL is http://docker.for.mac.host.internal:1000/api/v1/order/create/?count=1"
  - task: http
    in:
      method: GET
      url: "http://docker.for.mac.host.internal:1000/api/v1/order/create/?count=1"
      response: string
      out: jsonResponse
  - if: ${jsonResponse.success}
    then:
     - log: "Response received as ${jsonResponse.content}"
  - set:
      x: "${jsonResponse.content}"
  - script: my_logic1.py
  - log: "itemlist is ${itemlist} with counts as ${itemcounts}"
  - script: my_logic2.py
  - log: "Final count is ${finalcount}"

triggers:
- cron:
    spec: "* * * * *" # run every minute
    entryPoint: default
